package com.banco.entities;

public enum EmailType {
    WELCOME,
    EMAIL_VERIFICATION,
    TRANSACTION_VERIFICATION,
    EMAIL_MODIFICATION,
    PHONE_MODIFICATION,
    SIGN_MODIFICATION,
    ACCOUNT_DATA_MODIFICATION,
    NEW_LOGIN,
    CREATED_NEW_BANK_ACCOUNT,
    CREATED_NEW_CARD,
    CARD_SENT,
    CREATED_NEW_LOAN,
    UNPAID_LOAN_SUBSCRIPTION,
    COMPLETED_LOAN,
    RECALCULATED_LOAN,
    CARD_CHARGE,
    TRANSFER_RECEIVED,
    TRANSFER_SENT,

}
